# Use postgres/example user/password credentials
version: '3.9'

#...
services:

  #...
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - postgres-compose-network

  #...
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - polls_redis_data:/bitnami/redis/data

  #...
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL="carlosjuatan.workplace@gmail.com"
      - PGADMIN_DEFAULT_PASSWORD="car_J#09"
      - PGADMIN_CONFIG_SERVER_MODE='False'
    ports:
      - '16543:80'
    networks:
      - postgres-compose-network
    restart: unless-stopped

#...
volumes:
  polls_pg_data:
  polls_redis_data:

#..
networks: 
  postgres-compose-network:
    driver: bridge