version: '3.9'

#..
services:
  #..
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          #- node.role == worker
          #- node.hostname == database
      resources:
        limits:
          cpus: "1"
          memory: 2048M

  #..
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlosjuatan.workplace@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=car_J#09  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    links:
      - postgres


#..
volumes:
  postgres_data:
  pgadmin_data:

#..
networks:
  evolution-net:
    name: evolution-net
    driver: bridge
