version: '3.9'

#..
services:
  #..
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=DB
      # Habilitar o uso do banco de dados
      - DATABASE_ENABLED=true

      # Escolher o provedor do banco de dados: postgresql ou mysql
      - DATABASE_PROVIDER=postgresql

      # URI de conexão com o banco de dados
      - DATABASE_CONNECTION_URI='postgresql://user:pass@localhost:5432/evolution?schema=public'

      # Nome do cliente para a conexão do banco de dados
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_exchange

      # Escolha os dados que você deseja salvar no banco de dados da aplicação
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  #..
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlosjuatan.workplace@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=car_J#09 
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    networks:
      - evolution-net
    links:
      - postgres

#..
volumes:
  postgres_data:
  pgadmin_data:

#..
networks:
  evolution-net:
    name: evolution-net
    driver: bridge
