version: '3.7'

services:
  agent:
    image: portainer/agent:2.21.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.21.3
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    #ports:
    #  - 9443:9443
    #  - 9000:9000
    #  - 8000:8000
    #expose:
    #  - 9000:9000
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"

        # Endereço inseguro com o http
        - "traefik.http.routers.portainer_sem_https.rule=Host(`portainer.localhost`)"
        - "traefik.http.routers.portainer_sem_https.entrypoints=web"

        # Redirecionamento do http para o https
        - "traefik.http.middlewares.portainer_redirect_https.redirectscheme.scheme=https"
        - "traefik.http.routers.portainer_sem_https.middlewares=portainer_redirect_https"

        # Endereço seguro com o https
        - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls.certresolver=le"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data: